project_id = "atxwvjxbqjgkbjlhsdch"

[functions.register-student]
verify_jwt = false

[functions.student-chat]
verify_jwt = false

[functions.import-course]
verify_jwt = false

[functions.generate-course-structure]
verify_jwt = false
