project_id = "atxwvjxbqjgkbjlhsdch"

[functions.register-student]
verify_jwt = false

[functions.student-chat]
verify_jwt = false

[functions.import-course]
verify_jwt = false

[functions.generate-course-structure]
verify_jwt = false

[functions.generate-lesson-content]
verify_jwt = false

[functions.create-org-user]
verify_jwt = false

[functions.send-course-invitation]
verify_jwt = false

[functions.dadata-company]
verify_jwt = false

[functions.send-credentials]
verify_jwt = false

[functions.generate-explanation]
verify_jwt = false

[functions.process-contract-template]
verify_jwt = false
