// Auto-generated from ISO 3166 (ОКСМ). Codes match ОК 025-2001.
export interface OksmCountry { code: string; name: string; alpha2: string; alpha3: string; }
export const OKSM_COUNTRIES: OksmCountry[] = [
  { code: "036", name: "Австралия", alpha2: "AU", alpha3: "AUS" },
  { code: "040", name: "Австрия", alpha2: "AT", alpha3: "AUT" },
  { code: "031", name: "Азербайджан", alpha2: "AZ", alpha3: "AZE" },
  { code: "008", name: "Албания", alpha2: "AL", alpha3: "ALB" },
  { code: "012", name: "Алжир", alpha2: "DZ", alpha3: "DZA" },
  { code: "024", name: "Ангола", alpha2: "AO", alpha3: "AGO" },
  { code: "020", name: "Андорра", alpha2: "AD", alpha3: "AND" },
  { code: "028", name: "Антигуа и Барбуда", alpha2: "AG", alpha3: "ATG" },
  { code: "032", name: "Аргентина", alpha2: "AR", alpha3: "ARG" },
  { code: "051", name: "Армения", alpha2: "AM", alpha3: "ARM" },
  { code: "004", name: "Афганистан", alpha2: "AF", alpha3: "AFG" },
  { code: "044", name: "Багамские Острова", alpha2: "BS", alpha3: "BHS" },
  { code: "050", name: "Бангладеш", alpha2: "BD", alpha3: "BGD" },
  { code: "052", name: "Барбадос", alpha2: "BB", alpha3: "BRB" },
  { code: "048", name: "Бахрейн", alpha2: "BH", alpha3: "BHR" },
  { code: "112", name: "Беларусь", alpha2: "BY", alpha3: "BLR" },
  { code: "084", name: "Белиз", alpha2: "BZ", alpha3: "BLZ" },
  { code: "056", name: "Бельгия", alpha2: "BE", alpha3: "BEL" },
  { code: "204", name: "Бенин", alpha2: "BJ", alpha3: "BEN" },
  { code: "100", name: "Болгария", alpha2: "BG", alpha3: "BGR" },
  { code: "068", name: "Боливия", alpha2: "BO", alpha3: "BOL" },
  { code: "070", name: "Босния и Герцеговина", alpha2: "BA", alpha3: "BIH" },
  { code: "072", name: "Ботсвана", alpha2: "BW", alpha3: "BWA" },
  { code: "076", name: "Бразилия", alpha2: "BR", alpha3: "BRA" },
  { code: "096", name: "Бруней", alpha2: "BN", alpha3: "BRN" },
  { code: "854", name: "Буркина-Фасо", alpha2: "BF", alpha3: "BFA" },
  { code: "108", name: "Бурунди", alpha2: "BI", alpha3: "BDI" },
  { code: "064", name: "Бутан", alpha2: "BT", alpha3: "BTN" },
  { code: "548", name: "Вануату", alpha2: "VU", alpha3: "VUT" },
  { code: "826", name: "Великобритания", alpha2: "GB", alpha3: "GBR" },
  { code: "348", name: "Венгрия", alpha2: "HU", alpha3: "HUN" },
  { code: "862", name: "Венесуэла", alpha2: "VE", alpha3: "VEN" },
  { code: "626", name: "Восточный Тимор", alpha2: "TL", alpha3: "TLS" },
  { code: "704", name: "Вьетнам", alpha2: "VN", alpha3: "VNM" },
  { code: "266", name: "Габон", alpha2: "GA", alpha3: "GAB" },
  { code: "332", name: "Гаити", alpha2: "HT", alpha3: "HTI" },
  { code: "328", name: "Гайана", alpha2: "GY", alpha3: "GUY" },
  { code: "270", name: "Гамбия", alpha2: "GM", alpha3: "GMB" },
  { code: "288", name: "Гана", alpha2: "GH", alpha3: "GHA" },
  { code: "320", name: "Гватемала", alpha2: "GT", alpha3: "GTM" },
  { code: "324", name: "Гвинея", alpha2: "GN", alpha3: "GIN" },
  { code: "624", name: "Гвинея-Бисау", alpha2: "GW", alpha3: "GNB" },
  { code: "276", name: "Германия", alpha2: "DE", alpha3: "DEU" },
  { code: "340", name: "Гондурас", alpha2: "HN", alpha3: "HND" },
  { code: "308", name: "Гренада", alpha2: "GD", alpha3: "GRD" },
  { code: "300", name: "Греция", alpha2: "GR", alpha3: "GRC" },
  { code: "268", name: "Грузия", alpha2: "GE", alpha3: "GEO" },
  { code: "180", name: "ДР Конго", alpha2: "CD", alpha3: "COD" },
  { code: "208", name: "Дания", alpha2: "DK", alpha3: "DNK" },
  { code: "262", name: "Джибути", alpha2: "DJ", alpha3: "DJI" },
  { code: "212", name: "Доминика", alpha2: "DM", alpha3: "DMA" },
  { code: "214", name: "Доминиканская Республика", alpha2: "DO", alpha3: "DOM" },
  { code: "818", name: "Египет", alpha2: "EG", alpha3: "EGY" },
  { code: "894", name: "Замбия", alpha2: "ZM", alpha3: "ZMB" },
  { code: "716", name: "Зимбабве", alpha2: "ZW", alpha3: "ZWE" },
  { code: "376", name: "Израиль", alpha2: "IL", alpha3: "ISR" },
  { code: "356", name: "Индия", alpha2: "IN", alpha3: "IND" },
  { code: "360", name: "Индонезия", alpha2: "ID", alpha3: "IDN" },
  { code: "400", name: "Иордания", alpha2: "JO", alpha3: "JOR" },
  { code: "368", name: "Ирак", alpha2: "IQ", alpha3: "IRQ" },
  { code: "364", name: "Иран", alpha2: "IR", alpha3: "IRN" },
  { code: "372", name: "Ирландия", alpha2: "IE", alpha3: "IRL" },
  { code: "352", name: "Исландия", alpha2: "IS", alpha3: "ISL" },
  { code: "724", name: "Испания", alpha2: "ES", alpha3: "ESP" },
  { code: "380", name: "Италия", alpha2: "IT", alpha3: "ITA" },
  { code: "887", name: "Йемен", alpha2: "YE", alpha3: "YEM" },
  { code: "408", name: "КНДР (Корейская Народно-Демократическая Республика)", alpha2: "KP", alpha3: "PRK" },
  { code: "132", name: "Кабо-Верде", alpha2: "CV", alpha3: "CPV" },
  { code: "398", name: "Казахстан", alpha2: "KZ", alpha3: "KAZ" },
  { code: "116", name: "Камбоджа", alpha2: "KH", alpha3: "KHM" },
  { code: "120", name: "Камерун", alpha2: "CM", alpha3: "CMR" },
  { code: "124", name: "Канада", alpha2: "CA", alpha3: "CAN" },
  { code: "634", name: "Катар", alpha2: "QA", alpha3: "QAT" },
  { code: "404", name: "Кения", alpha2: "KE", alpha3: "KEN" },
  { code: "196", name: "Кипр", alpha2: "CY", alpha3: "CYP" },
  { code: "296", name: "Кирибати", alpha2: "KI", alpha3: "KIR" },
  { code: "156", name: "Китай (Китайская Народная Республика)", alpha2: "CN", alpha3: "CHN" },
  { code: "170", name: "Колумбия", alpha2: "CO", alpha3: "COL" },
  { code: "174", name: "Коморы", alpha2: "KM", alpha3: "COM" },
  { code: "188", name: "Коста-Рика", alpha2: "CR", alpha3: "CRI" },
  { code: "384", name: "Кот-д’Ивуар", alpha2: "CI", alpha3: "CIV" },
  { code: "192", name: "Куба", alpha2: "CU", alpha3: "CUB" },
  { code: "414", name: "Кувейт", alpha2: "KW", alpha3: "KWT" },
  { code: "417", name: "Кыргызстан", alpha2: "KG", alpha3: "KGZ" },
  { code: "418", name: "Лаос", alpha2: "LA", alpha3: "LAO" },
  { code: "428", name: "Латвия", alpha2: "LV", alpha3: "LVA" },
  { code: "426", name: "Лесото", alpha2: "LS", alpha3: "LSO" },
  { code: "430", name: "Либерия", alpha2: "LR", alpha3: "LBR" },
  { code: "422", name: "Ливан", alpha2: "LB", alpha3: "LBN" },
  { code: "434", name: "Ливия", alpha2: "LY", alpha3: "LBY" },
  { code: "440", name: "Литва", alpha2: "LT", alpha3: "LTU" },
  { code: "438", name: "Лихтенштейн", alpha2: "LI", alpha3: "LIE" },
  { code: "442", name: "Люксембург", alpha2: "LU", alpha3: "LUX" },
  { code: "480", name: "Маврикий", alpha2: "MU", alpha3: "MUS" },
  { code: "478", name: "Мавритания", alpha2: "MR", alpha3: "MRT" },
  { code: "450", name: "Мадагаскар", alpha2: "MG", alpha3: "MDG" },
  { code: "454", name: "Малави", alpha2: "MW", alpha3: "MWI" },
  { code: "458", name: "Малайзия", alpha2: "MY", alpha3: "MYS" },
  { code: "466", name: "Мали", alpha2: "ML", alpha3: "MLI" },
  { code: "462", name: "Мальдивы", alpha2: "MV", alpha3: "MDV" },
  { code: "470", name: "Мальта", alpha2: "MT", alpha3: "MLT" },
  { code: "504", name: "Марокко", alpha2: "MA", alpha3: "MAR" },
  { code: "584", name: "Маршалловы Острова", alpha2: "MH", alpha3: "MHL" },
  { code: "484", name: "Мексика", alpha2: "MX", alpha3: "MEX" },
  { code: "583", name: "Микронезия", alpha2: "FM", alpha3: "FSM" },
  { code: "508", name: "Мозамбик", alpha2: "MZ", alpha3: "MOZ" },
  { code: "498", name: "Молдова", alpha2: "MD", alpha3: "MDA" },
  { code: "492", name: "Монако", alpha2: "MC", alpha3: "MCO" },
  { code: "496", name: "Монголия", alpha2: "MN", alpha3: "MNG" },
  { code: "104", name: "Мьянма", alpha2: "MM", alpha3: "MMR" },
  { code: "516", name: "Намибия", alpha2: "NA", alpha3: "NAM" },
  { code: "520", name: "Науру", alpha2: "NR", alpha3: "NRU" },
  { code: "524", name: "Непал", alpha2: "NP", alpha3: "NPL" },
  { code: "562", name: "Нигер", alpha2: "NE", alpha3: "NER" },
  { code: "566", name: "Нигерия", alpha2: "NG", alpha3: "NGA" },
  { code: "528", name: "Нидерланды", alpha2: "NL", alpha3: "NLD" },
  { code: "558", name: "Никарагуа", alpha2: "NI", alpha3: "NIC" },
  { code: "554", name: "Новая Зеландия", alpha2: "NZ", alpha3: "NZL" },
  { code: "578", name: "Норвегия", alpha2: "NO", alpha3: "NOR" },
  { code: "784", name: "ОАЭ", alpha2: "AE", alpha3: "ARE" },
  { code: "512", name: "Оман", alpha2: "OM", alpha3: "OMN" },
  { code: "586", name: "Пакистан", alpha2: "PK", alpha3: "PAK" },
  { code: "585", name: "Палау", alpha2: "PW", alpha3: "PLW" },
  { code: "591", name: "Панама", alpha2: "PA", alpha3: "PAN" },
  { code: "598", name: "Папуа — Новая Гвинея", alpha2: "PG", alpha3: "PNG" },
  { code: "600", name: "Парагвай", alpha2: "PY", alpha3: "PRY" },
  { code: "604", name: "Перу", alpha2: "PE", alpha3: "PER" },
  { code: "616", name: "Польша", alpha2: "PL", alpha3: "POL" },
  { code: "620", name: "Португалия", alpha2: "PT", alpha3: "PRT" },
  { code: "178", name: "Республика Конго", alpha2: "CG", alpha3: "COG" },
  { code: "410", name: "Республика Корея", alpha2: "KR", alpha3: "KOR" },
  { code: "643", name: "Россия", alpha2: "RU", alpha3: "RUS" },
  { code: "646", name: "Руанда", alpha2: "RW", alpha3: "RWA" },
  { code: "642", name: "Румыния", alpha2: "RO", alpha3: "ROU" },
  { code: "840", name: "США", alpha2: "US", alpha3: "USA" },
  { code: "222", name: "Сальвадор", alpha2: "SV", alpha3: "SLV" },
  { code: "882", name: "Самоа", alpha2: "WS", alpha3: "WSM" },
  { code: "674", name: "Сан-Марино", alpha2: "SM", alpha3: "SMR" },
  { code: "678", name: "Сан-Томе и Принсипи", alpha2: "ST", alpha3: "STP" },
  { code: "682", name: "Саудовская Аравия", alpha2: "SA", alpha3: "SAU" },
  { code: "807", name: "Северная Македония", alpha2: "MK", alpha3: "MKD" },
  { code: "690", name: "Сейшельские Острова", alpha2: "SC", alpha3: "SYC" },
  { code: "686", name: "Сенегал", alpha2: "SN", alpha3: "SEN" },
  { code: "670", name: "Сент-Винсент и Гренадины", alpha2: "VC", alpha3: "VCT" },
  { code: "659", name: "Сент-Китс и Невис", alpha2: "KN", alpha3: "KNA" },
  { code: "662", name: "Сент-Люсия", alpha2: "LC", alpha3: "LCA" },
  { code: "688", name: "Сербия", alpha2: "RS", alpha3: "SRB" },
  { code: "702", name: "Сингапур", alpha2: "SG", alpha3: "SGP" },
  { code: "760", name: "Сирия", alpha2: "SY", alpha3: "SYR" },
  { code: "703", name: "Словакия", alpha2: "SK", alpha3: "SVK" },
  { code: "705", name: "Словения", alpha2: "SI", alpha3: "SVN" },
  { code: "090", name: "Соломоновы Острова", alpha2: "SB", alpha3: "SLB" },
  { code: "706", name: "Сомали", alpha2: "SO", alpha3: "SOM" },
  { code: "729", name: "Судан", alpha2: "SD", alpha3: "SDN" },
  { code: "740", name: "Суринам", alpha2: "SR", alpha3: "SUR" },
  { code: "694", name: "Сьерра-Леоне", alpha2: "SL", alpha3: "SLE" },
  { code: "762", name: "Таджикистан", alpha2: "TJ", alpha3: "TJK" },
  { code: "764", name: "Таиланд", alpha2: "TH", alpha3: "THA" },
  { code: "834", name: "Танзания", alpha2: "TZ", alpha3: "TZA" },
  { code: "768", name: "Того", alpha2: "TG", alpha3: "TGO" },
  { code: "776", name: "Тонга", alpha2: "TO", alpha3: "TON" },
  { code: "780", name: "Тринидад и Тобаго", alpha2: "TT", alpha3: "TTO" },
  { code: "798", name: "Тувалу", alpha2: "TV", alpha3: "TUV" },
  { code: "788", name: "Тунис", alpha2: "TN", alpha3: "TUN" },
  { code: "795", name: "Туркменистан", alpha2: "TM", alpha3: "TKM" },
  { code: "792", name: "Турция", alpha2: "TR", alpha3: "TUR" },
  { code: "800", name: "Уганда", alpha2: "UG", alpha3: "UGA" },
  { code: "860", name: "Узбекистан", alpha2: "UZ", alpha3: "UZB" },
  { code: "804", name: "Украина", alpha2: "UA", alpha3: "UKR" },
  { code: "858", name: "Уругвай", alpha2: "UY", alpha3: "URY" },
  { code: "242", name: "Фиджи", alpha2: "FJ", alpha3: "FJI" },
  { code: "608", name: "Филиппины", alpha2: "PH", alpha3: "PHL" },
  { code: "246", name: "Финляндия", alpha2: "FI", alpha3: "FIN" },
  { code: "250", name: "Франция", alpha2: "FR", alpha3: "FRA" },
  { code: "191", name: "Хорватия", alpha2: "HR", alpha3: "HRV" },
  { code: "140", name: "ЦАР", alpha2: "CF", alpha3: "CAF" },
  { code: "148", name: "Чад", alpha2: "TD", alpha3: "TCD" },
  { code: "499", name: "Черногория", alpha2: "ME", alpha3: "MNE" },
  { code: "203", name: "Чехия", alpha2: "CZ", alpha3: "CZE" },
  { code: "152", name: "Чили", alpha2: "CL", alpha3: "CHL" },
  { code: "756", name: "Швейцария", alpha2: "CH", alpha3: "CHE" },
  { code: "752", name: "Швеция", alpha2: "SE", alpha3: "SWE" },
  { code: "144", name: "Шри-Ланка", alpha2: "LK", alpha3: "LKA" },
  { code: "218", name: "Эквадор", alpha2: "EC", alpha3: "ECU" },
  { code: "226", name: "Экваториальная Гвинея", alpha2: "GQ", alpha3: "GNQ" },
  { code: "232", name: "Эритрея", alpha2: "ER", alpha3: "ERI" },
  { code: "748", name: "Эсватини", alpha2: "SZ", alpha3: "SWZ" },
  { code: "233", name: "Эстония", alpha2: "EE", alpha3: "EST" },
  { code: "231", name: "Эфиопия", alpha2: "ET", alpha3: "ETH" },
  { code: "710", name: "ЮАР", alpha2: "ZA", alpha3: "ZAF" },
  { code: "728", name: "Южный Судан", alpha2: "SS", alpha3: "SSD" },
  { code: "388", name: "Ямайка", alpha2: "JM", alpha3: "JAM" },
  { code: "392", name: "Япония", alpha2: "JP", alpha3: "JPN" },
];

export const OKSM_BY_CODE: Record<string, OksmCountry> = Object.fromEntries(OKSM_COUNTRIES.map(c => [c.code, c]));
export function getOksmName(code: string | null | undefined): string { if (!code) return ''; return OKSM_BY_CODE[String(code).padStart(3,'0')]?.name || code; }