-- Persistent, service-only rate limiting and idempotency for narrow Telegram
-- domain endpoints. Browser clients never call this RPC directly.
CREATE TABLE IF NOT EXISTS public.telegram_domain_rate_limits (
  id bigint GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  action text NOT NULL CHECK (action IN (
    'special_offer_request',
    'organization_registration',
    'support_request',
    'organization_telegram_test',
    'subscription_upgrade'
  )),
  actor_hash text NOT NULL CHECK (actor_hash ~ '^[0-9a-f]{64}$'),
  created_at timestamptz NOT NULL DEFAULT now()
);

CREATE INDEX IF NOT EXISTS telegram_domain_rate_limits_actor_window_idx
  ON public.telegram_domain_rate_limits (action, actor_hash, created_at DESC);

ALTER TABLE public.telegram_domain_rate_limits ENABLE ROW LEVEL SECURITY;
REVOKE ALL ON TABLE public.telegram_domain_rate_limits FROM PUBLIC, anon, authenticated;
GRANT SELECT, INSERT, DELETE ON TABLE public.telegram_domain_rate_limits TO service_role;
GRANT USAGE, SELECT ON SEQUENCE public.telegram_domain_rate_limits_id_seq TO service_role;

CREATE OR REPLACE FUNCTION public.claim_telegram_domain_delivery(
  _dedup_key text,
  _action text,
  _actor_hash text,
  _max_requests integer,
  _window_seconds integer
)
RETURNS text
LANGUAGE plpgsql
SECURITY DEFINER
SET search_path = public
AS $$
DECLARE
  _inserted boolean;
  _recent_count integer;
BEGIN
  IF length(coalesce(_dedup_key, '')) NOT BETWEEN 8 AND 300
    OR _action NOT IN (
      'special_offer_request',
      'organization_registration',
      'support_request',
      'organization_telegram_test',
      'subscription_upgrade'
    )
    OR _actor_hash !~ '^[0-9a-f]{64}$'
    OR _max_requests NOT BETWEEN 1 AND 100
    OR _window_seconds NOT BETWEEN 1 AND 86400
  THEN
    RAISE EXCEPTION 'invalid telegram delivery claim';
  END IF;

  -- Serialize one actor/action window. A separate unique insert below also
  -- protects one dedup key used concurrently by different actors.
  PERFORM pg_advisory_xact_lock(hashtextextended(_action || ':' || _actor_hash, 0));

  IF EXISTS (
    SELECT 1 FROM public.notification_dedup_log WHERE key = _dedup_key
  ) THEN
    RETURN 'duplicate';
  END IF;

  SELECT count(*)::integer
    INTO _recent_count
    FROM public.telegram_domain_rate_limits
   WHERE action = _action
     AND actor_hash = _actor_hash
     AND created_at >= now() - make_interval(secs => _window_seconds);

  IF _recent_count >= _max_requests THEN
    RETURN 'rate_limited';
  END IF;

  INSERT INTO public.notification_dedup_log(key)
  VALUES (_dedup_key)
  ON CONFLICT (key) DO NOTHING;
  GET DIAGNOSTICS _inserted = ROW_COUNT;

  IF NOT _inserted THEN
    RETURN 'duplicate';
  END IF;

  INSERT INTO public.telegram_domain_rate_limits(action, actor_hash)
  VALUES (_action, _actor_hash);

  -- Bounded cleanup for this actor only; the longest accepted window is 24 h.
  DELETE FROM public.telegram_domain_rate_limits
   WHERE action = _action
     AND actor_hash = _actor_hash
     AND created_at < now() - interval '2 days';

  RETURN 'claimed';
END;
$$;

REVOKE ALL ON FUNCTION public.claim_telegram_domain_delivery(text, text, text, integer, integer)
  FROM PUBLIC, anon, authenticated;
GRANT EXECUTE ON FUNCTION public.claim_telegram_domain_delivery(text, text, text, integer, integer)
  TO service_role;

-- The legacy helper had only an explicit service_role GRANT, but PostgreSQL
-- functions are executable by PUBLIC unless explicitly revoked.
REVOKE ALL ON FUNCTION public.claim_notification_dedup(text) FROM PUBLIC, anon, authenticated;
GRANT EXECUTE ON FUNCTION public.claim_notification_dedup(text) TO service_role;
