-- Persistent, service-only abuse controls for the public registration-attempt
-- logger. Only opaque HMAC digests are stored here; email, phone and IP values
-- remain outside these rate/dedupe tables.
CREATE TABLE IF NOT EXISTS public.registration_attempt_rate_limits (
  id bigint GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  scope text NOT NULL CHECK (scope IN (
    'event_client',
    'event_global',
    'failure_client',
    'failure_global'
  )),
  actor_hash text NOT NULL CHECK (actor_hash ~ '^[0-9a-f]{64}$'),
  created_at timestamptz NOT NULL DEFAULT now()
);

CREATE INDEX IF NOT EXISTS registration_attempt_rate_actor_window_idx
  ON public.registration_attempt_rate_limits (scope, actor_hash, created_at DESC);
CREATE INDEX IF NOT EXISTS registration_attempt_rate_created_idx
  ON public.registration_attempt_rate_limits (created_at);

ALTER TABLE public.registration_attempt_rate_limits ENABLE ROW LEVEL SECURITY;
REVOKE ALL ON TABLE public.registration_attempt_rate_limits FROM PUBLIC, anon, authenticated;
GRANT SELECT, INSERT, DELETE ON TABLE public.registration_attempt_rate_limits TO service_role;
GRANT USAGE, SELECT ON SEQUENCE public.registration_attempt_rate_limits_id_seq TO service_role;

CREATE TABLE IF NOT EXISTS public.registration_failure_alert_claims (
  dedup_hash text PRIMARY KEY CHECK (dedup_hash ~ '^[0-9a-f]{64}$'),
  actor_hash text NOT NULL CHECK (actor_hash ~ '^[0-9a-f]{64}$'),
  state text NOT NULL DEFAULT 'pending' CHECK (state IN ('pending', 'delivered')),
  lease_until timestamptz,
  delivered_at timestamptz,
  created_at timestamptz NOT NULL DEFAULT now(),
  updated_at timestamptz NOT NULL DEFAULT now()
);

CREATE INDEX IF NOT EXISTS registration_failure_alert_created_idx
  ON public.registration_failure_alert_claims (created_at);

ALTER TABLE public.registration_failure_alert_claims ENABLE ROW LEVEL SECURITY;
REVOKE ALL ON TABLE public.registration_failure_alert_claims FROM PUBLIC, anon, authenticated;
GRANT SELECT, INSERT, UPDATE, DELETE ON TABLE public.registration_failure_alert_claims TO service_role;

CREATE OR REPLACE FUNCTION public.claim_registration_attempt_rate(
  _scope text,
  _actor_hash text,
  _max_requests integer,
  _window_seconds integer
)
RETURNS text
LANGUAGE plpgsql
SECURITY DEFINER
SET search_path = public, pg_temp
AS $$
DECLARE
  _recent_count integer;
BEGIN
  IF _scope NOT IN ('event_client', 'event_global', 'failure_client', 'failure_global')
    OR _actor_hash !~ '^[0-9a-f]{64}$'
    OR _max_requests NOT BETWEEN 1 AND 1000
    OR _window_seconds NOT BETWEEN 1 AND 86400
  THEN
    RAISE EXCEPTION 'invalid registration attempt rate claim';
  END IF;

  PERFORM pg_advisory_xact_lock(hashtextextended(_scope || ':' || _actor_hash, 0));

  SELECT count(*)::integer
    INTO _recent_count
    FROM public.registration_attempt_rate_limits
   WHERE scope = _scope
     AND actor_hash = _actor_hash
     AND created_at >= now() - make_interval(secs => _window_seconds);

  IF _recent_count >= _max_requests THEN
    RETURN 'rate_limited';
  END IF;

  -- Every call inserts a row, including a byte-for-byte replay. Dedupe is a
  -- separate concern and cannot bypass the public endpoint's request budget.
  INSERT INTO public.registration_attempt_rate_limits(scope, actor_hash)
  VALUES (_scope, _actor_hash);

  DELETE FROM public.registration_attempt_rate_limits
   WHERE created_at < now() - interval '2 days';

  RETURN 'allowed';
END;
$$;

CREATE OR REPLACE FUNCTION public.claim_registration_failure_alert(
  _actor_hash text,
  _dedup_hash text,
  _lease_seconds integer
)
RETURNS text
LANGUAGE plpgsql
SECURITY DEFINER
SET search_path = public, pg_temp
AS $$
DECLARE
  _existing public.registration_failure_alert_claims%ROWTYPE;
BEGIN
  IF _actor_hash !~ '^[0-9a-f]{64}$'
    OR _dedup_hash !~ '^[0-9a-f]{64}$'
    OR _lease_seconds NOT BETWEEN 30 AND 3600
  THEN
    RAISE EXCEPTION 'invalid registration failure alert claim';
  END IF;

  PERFORM pg_advisory_xact_lock(hashtextextended('registration-failure:' || _dedup_hash, 0));

  SELECT * INTO _existing
    FROM public.registration_failure_alert_claims
   WHERE dedup_hash = _dedup_hash;

  IF FOUND AND _existing.state = 'delivered' THEN
    RETURN 'duplicate';
  END IF;
  IF FOUND AND _existing.lease_until IS NOT NULL AND _existing.lease_until > now() THEN
    RETURN 'duplicate';
  END IF;

  INSERT INTO public.registration_failure_alert_claims(
    dedup_hash,
    actor_hash,
    state,
    lease_until,
    delivered_at,
    updated_at
  ) VALUES (
    _dedup_hash,
    _actor_hash,
    'pending',
    now() + make_interval(secs => _lease_seconds),
    NULL,
    now()
  )
  ON CONFLICT (dedup_hash) DO UPDATE
    SET actor_hash = EXCLUDED.actor_hash,
        state = 'pending',
        lease_until = EXCLUDED.lease_until,
        delivered_at = NULL,
        updated_at = now();

  DELETE FROM public.registration_failure_alert_claims
   WHERE created_at < now() - interval '2 days';

  RETURN 'claimed';
END;
$$;

CREATE OR REPLACE FUNCTION public.complete_registration_failure_alert(
  _dedup_hash text,
  _delivered boolean,
  _retry_after_seconds integer DEFAULT 300
)
RETURNS void
LANGUAGE plpgsql
SECURITY DEFINER
SET search_path = public, pg_temp
AS $$
BEGIN
  IF _dedup_hash !~ '^[0-9a-f]{64}$'
    OR _retry_after_seconds NOT BETWEEN 30 AND 3600
  THEN
    RAISE EXCEPTION 'invalid registration failure alert completion';
  END IF;

  IF _delivered THEN
    UPDATE public.registration_failure_alert_claims
       SET state = 'delivered',
           lease_until = NULL,
           delivered_at = now(),
           updated_at = now()
     WHERE dedup_hash = _dedup_hash;
  ELSE
    -- An Edge-to-Edge error can be ambiguous. Retain a short lease instead of
    -- immediately resending; the next failure may safely retry after the TTL.
    UPDATE public.registration_failure_alert_claims
       SET state = 'pending',
           lease_until = now() + make_interval(secs => _retry_after_seconds),
           updated_at = now()
     WHERE dedup_hash = _dedup_hash;
  END IF;
END;
$$;

REVOKE ALL ON FUNCTION public.claim_registration_attempt_rate(text, text, integer, integer)
  FROM PUBLIC, anon, authenticated;
GRANT EXECUTE ON FUNCTION public.claim_registration_attempt_rate(text, text, integer, integer)
  TO service_role;

REVOKE ALL ON FUNCTION public.claim_registration_failure_alert(text, text, integer)
  FROM PUBLIC, anon, authenticated;
GRANT EXECUTE ON FUNCTION public.claim_registration_failure_alert(text, text, integer)
  TO service_role;

REVOKE ALL ON FUNCTION public.complete_registration_failure_alert(text, boolean, integer)
  FROM PUBLIC, anon, authenticated;
GRANT EXECUTE ON FUNCTION public.complete_registration_failure_alert(text, boolean, integer)
  TO service_role;
