package ru.sintagma.app;

import android.os.Bundle;
import android.view.View;
import android.webkit.URLUtil;
import org.json.JSONObject;
import androidx.activity.OnBackPressedCallback;
import androidx.core.graphics.Insets;
import androidx.core.view.ViewCompat;
import androidx.core.view.WindowInsetsCompat;
import com.getcapacitor.BridgeActivity;

public class MainActivity extends BridgeActivity {
    @Override
    public void onCreate(Bundle savedInstanceState) {
        registerPlugin(NativeFilesPlugin.class);
        registerPlugin(NativeSpeechPlugin.class);
        super.onCreate(savedInstanceState);
        if (bridge == null) return; // Capacitor shows its missing-WebView screen.

        // HashRouter navigation must participate in the Android Back gesture.
        getOnBackPressedDispatcher().addCallback(this, new OnBackPressedCallback(true) {
            @Override
            public void handleOnBackPressed() {
                // Radix dialogs do not create a history entry. Give the visible
                // dialog its ordinary Escape action before navigating/exiting.
                String dismissDialog = "(function(){var dialog=Array.from(document.querySelectorAll('[role=dialog],[role=alertdialog]')).find(function(e){return e.getClientRects().length>0;});if(!dialog)return false;(document.activeElement||document.body).dispatchEvent(new KeyboardEvent('keydown',{key:'Escape',code:'Escape',bubbles:true,cancelable:true}));return true;})()";
                bridge.getWebView().evaluateJavascript(dismissDialog, handled -> {
                    if ("true".equals(handled)) return;
                    if (bridge.getWebView().canGoBack()) bridge.getWebView().goBack();
                    else moveTaskToBack(true);
                });
            }
        });

        // Keep controls outside the status/navigation bars on Android 15+.
        View content = findViewById(android.R.id.content);
        ViewCompat.setOnApplyWindowInsetsListener(content, (view, windowInsets) -> {
            Insets bars = windowInsets.getInsets(WindowInsetsCompat.Type.systemBars());
            view.setPadding(bars.left, bars.top, bars.right, bars.bottom);
            return windowInsets;
        });
        ViewCompat.requestApplyInsets(content);

        // WebView also receives detached links generated by PDF/FileSaver.
        // Pass the URL to the bundled app while it can still read its Blob.
        bridge.getWebView().setDownloadListener((url, userAgent, disposition, mime, length) -> {
            String fileName = URLUtil.guessFileName(url, disposition, mime);
            String script = "window.dispatchEvent(new CustomEvent('sintagma:native-download',{detail:{url:"
                + JSONObject.quote(url) + ",fileName:" + JSONObject.quote(fileName) + "}}))";
            bridge.getWebView().evaluateJavascript(script, null);
        });
    }
}
